### PR TITLE
Coding improvements

### PR DESCRIPTION
**Pull request by afragen**
I've made a number of things better, I think. 

Still getting an error with the `$wp_filesystem->move` and I don't know why. Similar code works elsewhere. Only thing I can see is that in other upgrades the download is in a nested folder and it's not here.

### CODE REVIEW

**Comment by afragen** [comment]
And with the final 2 commits it works. Ugly, but functional.

**Comment by seb86** [comment]
Wow @afragen. You really went beyond what I asked for. Thank you for spending your time on this. I will give it a try and report back to you.

**Comment by afragen** [comment]
I guess Hacktoberfest 🎃 isn’t just about hacking on your own code. 😉
Hopefully this fixes #1 and then some.

I think the primary issue was that WP expects the downloaded plugin to be inside of a directory. Every other download link I’ve encountered in GitHub does this. I have no idea why this particular download link does not. Essentially what I had to do to fix was to create that nested structure.

**Comment by afragen** [comment]
I just thought of something else to try regarding the download and directory issue. 🧐

**Comment by afragen** [comment]
With the commit 
https://github.com/seb86/gutenberg-prototype/pull/2/commits/dacc483ed37c06f057644620ef45a447d8b2c096 a new config variable `release_asset` must be set according to your project. 

The code is now a bit more versatile depending upon whether or not the pre-release requires a build process.

**Comment by seb86** [comment]
Sorry @afragen but this does not appear to be working due to read and write with the directory and the Gutenberg plugin folder now becomes empty.

**Comment by afragen** [comment]
That would happen if the renaming wasn’t working. But it does work in my testing. 

I’m traveling for a few days but I’ll check again when I get back.

**Comment by afragen** [comment]
Did you add the additional config setting for `release_asset`? https://github.com/seb86/gutenberg-prototype/commit/dacc483ed37c06f057644620ef45a447d8b2c096

The purpose of that was so you could reuse this code for your other updaters.

**Comment by seb86** [comment]
@afragen I downloaded your fork to test and it failed and produced more errors with attempting to move or rename the folder. It might be a bit difficult to test any further at this time as Gutenberg 4.0 was released today.

**Comment by afragen** [comment]
That’s too bad. I wonder if it’s a permissions issue. I thought I was able to overcome all of those issues. 

Now I’m curious. I’ll have to create another test install and see if I can replicate these issues. 

Do you see anything in your debug.log?

**Comment by seb86** [comment]
I have applied improvements of my own and created a [new branch](https://github.com/seb86/gutenberg-prototype/tree/correct-source) to focus on correcting the upgrader source. I have pushed a more direct approach but I am unable to test now that Gutenberg v4.0 is released so we will have to wait until another one is put forward.

**Comment by afragen** [comment]
Yeah not being able to actually see the code running is problematic. 🤷🏻‍♂️

**Comment by afragen** [comment]
Since there is a new release candidate I have been able to test more.

The current patch works on my end. I tested both with a local single site install of WP 4.9.8 and with a multisite install running WP 5.1alpha on my test server on Siteground.

Posting your error/debug logs would be helpful. I can't tell why it doesn't seem to work on your end - yet.

**Pull request closed without merging**
